### ISSUE TITLE
GUI - Browserkompatibilität

### ISSUE THREAD

**Issue by Phantomias2006** [WLANThermo/WLANThermo_v3#5]
Spricht etwas dagegen wenn wir IE 6-8 nicht mehr unterstützen?
Ich möchte im GUI jQuery einsetzen und würde hier auf die neue Version 3.x.x umstellen. Ab Version 3 wird IE6-8 nicht mehr unterstützt.

**Comment by BjoernSch** [comment]
Wer IE6-8 verwendet ist selbst Schuld, denke ich.

**Comment by Phantomias2006** [comment]
Perfekt.
